### PR TITLE
Finish issue 33

### PR DESCRIPTION
**Pull request by DavidjohnBlodgett**
WIP PR

Resolves RackHD/RackHD#33

@benbp @heckj I'll keep posting up to this, for your feed back as I make progress...

### CODE REVIEW

**Comment by benbp** [comment]
👍 

FYI if you say "Resolves https://github.com/RackHD/RackHD/issues/33" it will automatically close that issue when this is merged.

**Comment by yyscamper** [comment]
:+1:

**Comment by anhou** [comment]
:+1:

**Comment by DavidjohnBlodgett** [comment]
@benbp understood, ty

**Comment by yyscamper** [comment]
:+1:

**Pull request merged**
