### PR TITLE
[manifest] #1 add library for manifest build tools

### PR DESCRIPTION
**Pull request by PengTian0**
Add library for manfiest build tools.
The proposal of manifest build in rackhd release  is [here](https://groups.google.com/forum/#!topic/rackhd/v3LpRuQJvQg).

### CODE REVIEW

**Comment by PengTian0** [comment]
@panpan0000

**Comment by rackhd-test-rel** [comment]
Those library scripts comes from OnRack and was running stable for a long time. so :+1: to me

**Comment by PengTian0** [comment]
@RackHD/corecommitters

**Comment by panpan0000** [comment]
the @rackhd-test-rel  is me .... :cry:    :+1: 
* the GitBit seems necessary for Git Op with credential 
* the parallel task helps to speed up  multiple on-xxx repo  clone

**Pull request merged**
