### PR TITLE
Delete rackhd.py

### PR DESCRIPTION
**Pull request by keedya**
rackHd.py moved to https://github.com/ansible/ansible/blob/devel/contrib/inventory/rackhd.py

### CODE REVIEW

**Comment by keedya** [comment]
@zyoung51 @jlongever @benbp

**Comment by benbp** [comment]
:+1:

**Comment by keedya** [comment]
@tannoa2 @uppalk1

**Comment by yyscamper** [comment]
:+1:

**Comment by DavidjohnBlodgett** [comment]
:+1:

**Comment by anhou** [comment]
:+1:

**Pull request merged**
